### ISSUE TITLE
broken security call out box link on The Protocol page

### ISSUE THREAD

**Issue by joylarkin** [zerotier/docs#113]
On the security call out box on this page, https://docs.zerotier.com/protocol/#213cryptographyaname2_1_3a
the link is broken. 

I looked in the page markdown file and the call out box uses a relative link reference [security] which links to https://docs.zerotier.com/protocol/security and not https://docs.zerotier.com/security

<img width="735" alt="Screenshot 2023-11-30 at 10 13 09 AM" src="https://github.com/zerotier/docs/assets/10426780/4f767309-a602-4cfe-ad09-152f284a28f7">

Note: a sales prospect found the broken link and complained about it. (I am submitting this fix before the sales team sees the complaint.)

**Comment by laduke** [comment]
seems to be fixed
