### ISSUE TITLE
SVG version of ZeroTier icon?

### ISSUE THREAD

**Issue by loganmarchione** [zerotier/docs#50]
Hello there! 👋

I'm the maintainer of [homelab-svg-assets](https://github.com/loganmarchione/homelab-svg-assets) and would like to add the [ZeroTier icon](https://github.com/zerotier/docs/blob/main/static/img/ZeroTierIcon.png) to my project. However, I didn't see any brand guidelines or a vector (SVG) version of the icon. Could you please provide one or both of these?

Thanks, and keep up the good work!

**Comment by laduke** [comment]
hey thanks for asking. we have some. let us figure out how where to put them in public.

**Comment by joylarkin** [comment]
Hi @loganmarchione ... so sorry about the delay, I had this on my checklist but I lost track of who asked. Here are the in-use versions of the ZeroTier logo (2023 version) as svg files. 


![ZT icon gold black](https://github.com/zerotier/docs/assets/10426780/c2ad890a-8559-46f4-95a1-beb67680b1ce)
![ZT full logo gold black](https://github.com/zerotier/docs/assets/10426780/c5fce489-94e5-4f6d-a274-bd7ce0113bd8)
![ZT full logo white](https://github.com/zerotier/docs/assets/10426780/a8615c05-8fb5-4182-9554-faf463d7
![ZT full logo black](https://github.com/zerotier/docs/assets/10426780/1df8cbf3-72a4-46b5-976e-900f60e5a1cd)
a5b5)

**Comment by loganmarchione** [comment]
@joylarkin thanks!

Not to be a pain, but these appear to be PNG files wrapped in the SVG format (if you open them with a text editor, you can see the PNG data). Do you have pure SVGs of these?

**Comment by joylarkin** [comment]
Hi @loganmarchione - Sorry about this, I see what you are seeing. I have to go and find out how the logos were created, etc. I'll ping you when I have pure versions.
